- name: Create Internet Gateway
  community.aws.ec2_vpc_igw:
    region: "{{ aws_region }}"
    vpc_id: "{{ create_vpc.vpc.id }}"
    tags:
      Environment: "{{ ec2_environment }}"
      Name: "{{ ec2_resource_prefix }}-igw"
  register: create_igw
  until: create_igw is not failed
  retries: 5