- name: Create Route Table
  community.aws.ec2_vpc_route_table:
    region: "{{ aws_region }}"
    vpc_id: "{{ create_vpc.vpc.id }}"
    subnets:
      - "{{ create_subnet_1.subnet.id }}"
      - "{{ create_subnet_2.subnet.id }}"
    routes:
      - dest: 0.0.0.0/0
        gateway_id: "{{ create_igw.gateway_id }}"
    tags:
      Environment: "{{ ec2_environment }}"
      Name: "{{ ec2_resource_prefix }}-route-table"
  register: rt_table
  until: rt_table is not failed
  retries: 5