- name: Delete EKS Cluster tasks
  include_tasks: delete_eks.yml

- name: Delete IAM role tasks
  include_tasks: delete_iam_role.yml

- name: Delete Security Group tasks
  include_tasks: delete_security_group.yml

- name: Grab VPC details
  amazon.aws.ec2_vpc_net_info:
    region: "{{ aws_region }}"
    filters:
      "tag:Environment": "{{ ec2_environment }}"
  register: all_vpcs

- name: Delete Route Table tasks
  include_tasks: delete_rt_table.yml

- name: Delete Internet Gateway tasks
  include_tasks: delete_igw.yml

- name: Delete Subnet tasks
  include_tasks: delete_subnet.yml

- name: Delete VPC tasks
  include_tasks: delete_vpc.yml

- name: Delete SSH Key Pair tasks
  include_tasks: delete_key_pair.yml






