- name: Check that Cloud Provider selected is supported
  ansible.builtin.assert: { that: "cloud_provider in supported_clouds" }

- name: Include cloud-specific checks
  ansible.builtin.include_tasks: "{{ cloud_provider }}.yml"