# Ansible Lint for GitHub Action: https://github.com/marketplace/actions/ansible-lint
name: Ansible Lint

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: ansible-lint
      uses: ansible/ansible-lint-action@v4.1.0
      with:
        targets: "*.yml"
        # Avoid annoying 'File permissions not mentioned'
        args: "-x 208"